### ISSUE TITLE
LSL-API "WEAR" command is not replacing attachments

### ISSUE THREAD

**Issue by JHanivers** [CasperTech/METAbolt#16]
Since 1-27-2015, the "WEAR" folder command is not replacing outfits and the attachments for the called folder following the "WEAR" command are not being worn.  This also seems to be a problem with Metanomy's "WEAR" command and the "Changer" option in the Inventory tab.  

Other METAbolt users have verified this problem, the last update/maintenance to SL seems to have broken this command.

**Comment by Therealrosa** [comment]
Is there a chance that this problem will be solved?

**Comment by TomMettam** [comment]
METAbolt is an open source project. Any member of the community can contribute code to the project at any time.
