### ISSUE TITLE
Invtory not loading

### ISSUE THREAD

**Issue by GenoLupindo** [CasperTech/METAbolt#19]
I have tried a few different SL accounts and 2 different workstations inventory will not load in MetaBolt 9..71

**Comment by KindaFallen** [comment]
This started about the time the notice came on about the forum's server problem, I have not had inventory or favorites to load since then. Hoping to see at least a comment here from a mod, thank you.

**Comment by GenoLupindo** [comment]
Why would you close this with out comment ?

**Comment by TomMettam** [comment]
This issue is related to a caps problem and the eventqueue.

Going forward, the current version of metabolt is being abandoned in favour of a radegast-based fork which will be METAbolt 2, which is significantly more maintainable.

**Comment by GenoLupindo** [comment]
Will METAbolt 2 use the add-on like Group man will it still work to invite to groups and will it have group management for posts and IM's to many groups at the same time? Asking because this is the first I'm hearing about all of this and can find no info.
