### ISSUE TITLE
Inventory Not Loading

### ISSUE THREAD

**Issue by ZainDarkwatch** [CasperTech/METAbolt#21]
I have been using METAbolt for 2 or more years, usually without any hiccups; however, on 4/6/2015 I started having inventory issues.  I have tried restarting the program, my computer, clean uninstall and reinstall, to no avail.  All accounts which load up on the program, for some odd reason do not load their inventory.  I open all folders and they only ever say "Loading" or "Empty" (Which I know they have items in them, I have logged into Firestorm and the items show in the folders)

**Comment by TomMettam** [comment]
Duplicate issue

**Comment by KindaFallen** [comment]
Ditto here, exactly as you describe.
